server:
  port: 8002

spring:
  application:
    name: auth-service

security:
  jwt:
    uri: /auth/**
    header: Token
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

user-service:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

ribbon:
  eureka:
    enabled: true
