spring:
  profiles:
    active: common
  application:
    name: user-service

server:
  port: 8003

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

logging:
  level:
    org.hibernate.type: debug

ribbon:
  eureka:
    enabled: true

security:
  jwt:
    uri: /auth/**
    header: Token
    prefix: Bearer
    expiration: 86400 # 24*60*60
    secret: JwtSecretKey

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:~/user-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console

---
spring.profiles: release
spring.profiles.include: real-db
